sudo: false
language: node_js
node_js:
  - "8"
  - "10"
  - "12"
  - "14"
before_install:
  - if [[ `npm -v` =~ ^[1-2] ]]; then npm i -g npm@3; fi
before_script:
  - npm uninstall grunt # https://github.com/npm/npm/issues/3958
matrix:
  fast_finish: true
